// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOhPyEHeIqamui_mxLM_ajX3Q5NyiDHrY',
    appId: '1:383179116609:web:6a370bed717489103d36c0',
    messagingSenderId: '383179116609',
    projectId: 'foodies-e099a',
    authDomain: 'foodies-e099a.firebaseapp.com',
    storageBucket: 'foodies-e099a.firebasestorage.app',
    measurementId: 'G-LC0RSXRP2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOhPyEHeIqamui_mxLM_ajX3Q5NyiDHrY',
    appId: '1:383179116609:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '383179116609',
    projectId: 'foodies-e099a',
    storageBucket: 'foodies-e099a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOhPyEHeIqamui_mxLM_ajX3Q5NyiDHrY',
    appId: '1:383179116609:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '383179116609',
    projectId: 'foodies-e099a',
    storageBucket: 'foodies-e099a.firebasestorage.app',
    iosBundleId: 'com.example.foodiesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOhPyEHeIqamui_mxLM_ajX3Q5NyiDHrY',
    appId: '1:383179116609:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '383179116609',
    projectId: 'foodies-e099a',
    storageBucket: 'foodies-e099a.firebasestorage.app',
    iosBundleId: 'com.example.foodiesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOhPyEHeIqamui_mxLM_ajX3Q5NyiDHrY',
    appId: '1:383179116609:web:6a370bed717489103d36c0',
    messagingSenderId: '383179116609',
    projectId: 'foodies-e099a',
    authDomain: 'foodies-e099a.firebaseapp.com',
    storageBucket: 'foodies-e099a.firebasestorage.app',
    measurementId: 'G-LC0RSXRP2P',
  );
}